# Generated by Django 6.0.3 on 2026-03-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0002_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vitals',
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medflow.consultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflow.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medflow.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medflow.doctor'),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
