# Generated by Django 6.0.3 on 2026-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0005_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
