# Generated by Django 6.0.3 on 2026-03-20 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0006_consultation_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='notes',
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to='medflow.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medflow.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments_given', to='medflow.doctor'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medflow.patient'),
        ),
    ]
