# Generated by Django 6.0.3 on 2026-03-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0009_prescription_medical_record_treatment_medical_record_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
