# Generated by Django 6.0.3 on 2026-03-21 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0012_alter_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='consultation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='symptoms',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 21, 13, 35, 40, 340249, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medflow.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medflow.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
