# Generated by Django 6.0.3 on 2026-03-21 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0013_rename_consultation_date_consultation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='notes',
            new_name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='time',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
