# Generated by Django 6.0.3 on 2026-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0014_rename_notes_consultation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
