# Generated by Django 6.0.3 on 2026-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0016_doctor_first_name_doctor_last_name_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
