# Generated by Django 6.0.3 on 2026-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0017_doctor_is_deleted_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
