# Generated by Django 6.0.3 on 2026-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflow', '0018_patient_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
